FROM --platform=linux/amd64 docker.io/library/ubuntu:22.04
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:22.04"

### ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive
ARG PTI_VERSION="0.0.4"
ARG PTI_NO_COLOR="true"
ARG PTI_LOG_FORMAT="json"

ARG PACKAGE_MANAGER_VERSION="2024.11.0-7"

ENV PPM_LICENSE ""
ENV PPM_LICENSE_SERVER ""
ENV PPM_LICENSE_FILE_PATH ""
ENV STARTUP_DEBUG_MODE 0

### Install Posit Tool Installer ###
# FIXME(ianpittwood): Uncomment when PTI is available as a public repository
#ADD --chmod=0755 \
#    https://github.com/posit-dev/pti/releases/download/v${PTI_VERSION}/pti_${PTI_VERSION}_linux_amd64 \
#    /usr/local/bin/pti
# FIXME(ianpittwood): This is a shim to get around Github private repo authentication. ADD is a better solution once
#                     pti is available publicly.
COPY --chmod=0755 ./tools/pti /usr/local/bin/pti

### Initialize PTI in container ###
RUN pti init

### Install Apt Packages ###
COPY package-manager/2024.11.0-7/deps/ubuntu2204_packages.txt /tmp/packages.txt
RUN pti syspkg update \
    && pti syspkg upgrade --dist \
    && pti syspkg install -f /tmp/packages.txt \
    && rm -f /tmp/packages.txt

### Install tini ###
RUN pti container tini install



### Install Package Manager 2024.11.0-7 ###
COPY --chmod=0755 package-manager/2024.11.0-7/scripts/install_package_manager.sh /tmp/install_package_manager.sh
RUN /tmp/install_package_manager.sh \
    && rm -f /tmp/install_package_manager.sh

### Add startup.sh script ###
COPY --chmod=0775 package-manager/2024.11.0-7/scripts/startup.sh /usr/local/bin/startup.sh
RUN mkdir -p /var/run/rstudio-pm \
    && chmod +x /usr/local/bin/startup.sh \
    && chown rstudio-pm:rstudio-pm /usr/local/bin/startup.sh \
    && chown -R rstudio-pm:rstudio-pm /var/run/rstudio-pm

USER rstudio-pm

RUN echo "source <(rspm completion bash)" >> ~/.bashrc



CMD ["/usr/local/bin/startup.sh"]
