# Build Python using uv in a separate stage
FROM ghcr.io/astral-sh/uv:debian-slim AS python-builder

ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy
ENV UV_PYTHON_INSTALL_DIR=/opt/python
ENV UV_PYTHON_PREFERENCE=only-managed
RUN uv python install 3.14.5
RUN mv /opt/python/cpython-3.14.5-linux-*/ /opt/python/3.14.5


FROM registry.access.redhat.com/ubi10/ubi:10.2
LABEL org.opencontainers.image.base.name="registry.access.redhat.com/ubi10/ubi:10.2"

### ARG declarations ###
ARG TARGETARCH
ARG PACKAGE_MANAGER_VERSION="2026.05.0"

ENV PPM_LICENSE=""
ENV PPM_LICENSE_SERVER=""
ENV PPM_LICENSE_FILE_PATH=""
ENV PPM_STARTUP_DEBUG=0

SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

### Setup environment (upgrades packages + installs curl/tar/gnupg + configures Posit Pro repo) ###
RUN dnf upgrade -yq && \
    dnf install -yq --allowerasing \
        curl \
        ca-certificates \
        findutils \
        gnupg \
        tar && \
    bash -c "$(curl -1fsSL 'https://dl.posit.co/public/pro/setup.rpm.sh')" && \
    dnf clean all -yq

### Install dnf packages ###
COPY package-manager/2026.05/deps/rhel-10_packages.txt /tmp/packages.txt
RUN xargs -a /tmp/packages.txt dnf install -yq && \
    dnf clean all -yq

### Install Python from previous stage ###
COPY --from=python-builder /opt/python /opt/python

### Install Python packages ###
COPY package-manager/2026.05/deps/python_requirements.txt /tmp/requirements.txt
RUN /opt/python/3.14.5/bin/pip install --no-cache-dir --upgrade --break-system-packages \
        -r /tmp/requirements.txt && \
    rm -f /tmp/requirements.txt

### Install R ###
RUN RUN_UNATTENDED=1 R_VERSION=4.6.0 bash -c "$(curl -fsSL https://rstd.io/r-install)" && \
    find . -type f -name '[rR]-4.6.0.*\.(deb|rpm)' -delete

### Install Package Manager 2026.05.0 ###
COPY --chmod=0755 package-manager/2026.05/scripts/install_package_manager.rhel10.sh /tmp/install_package_manager.sh
RUN PYTHON_VERSION=3.14.5 R_VERSION=4.6.0 \
    /tmp/install_package_manager.sh \
    && rm -f /tmp/install_package_manager.sh

### Add startup.sh script ###
COPY --chmod=0775 package-manager/2026.05/scripts/startup.sh /usr/local/bin/startup.sh
RUN mkdir -p /var/run/rstudio-pm \
    && chmod +x /usr/local/bin/startup.sh \
    && chown rstudio-pm:rstudio-pm /usr/local/bin/startup.sh \
    && chown -R rstudio-pm:rstudio-pm /var/run/rstudio-pm

USER rstudio-pm

RUN echo "source <(rspm completion bash)" >> ~/.bashrc

HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 \
    CMD curl -fsS http://localhost:4242/__ping__ || exit 1

CMD ["/usr/local/bin/startup.sh"]
