ARG BASE_IMAGE_REGISTRY=docker.io
{% if not is_minimal -%}
ARG PYTHON_VERSION="{{ python_version }}"
ARG R_VERSION="{{ r_version }}"
FROM ${BASE_IMAGE_REGISTRY}/posit/base:ubuntu2204
{%- else -%}
FROM ${BASE_IMAGE_REGISTRY}/posit/base:ubuntu2204-min
{%- endif %}

### ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive
ARG SCRIPTS_DIR=/opt/posit/scripts
{%- if not is_minimal %}
ARG PYTHON_VERSION="{{ python_version }}"
ARG R_VERSION="{{ r_version }}"
{%- endif %}
ARG PACKAGE_MANAGER_VERSION="{{ image_version }}"

ENV PPM_LICENSE ""
ENV PPM_LICENSE_SERVER ""
ENV PPM_LICENSE_FILE_PATH ""
ENV STARTUP_DEBUG_MODE 0

### Install Apt Packages ###
COPY {{ rel_path }}/deps/ubuntu2204_packages.txt /tmp/ubuntu2204_packages.txt
RUN $SCRIPTS_DIR/apt.sh --update upgrade \
    && $SCRIPTS_DIR/apt.sh install $(cat /tmp/ubuntu2204_packages.txt) \
    && rm -f /tmp/packages.txt \
    && $SCRIPTS_DIR/apt.sh --clean
{% if not is_minimal -%}
### Install Python packages ###
COPY {{ rel_path }}/deps/python_requirements.txt /tmp/python_requirements.txt
RUN $SCRIPTS_DIR/install_python.sh -r /tmp/python_requirements.txt -- ${PYTHON_VERSION} \
    && rm -f /tmp/python_requirements.txt
{%- endif %}
### Install Package Manager {{ image_version }} ###
COPY {{ rel_path }}/scripts/install_package_manager.sh /tmp/install_package_manager.sh
RUN /tmp/install_package_manager.sh \
    && rm -f /tmp/install_package_manager.sh

### Add startup.sh script ###
COPY --chmod=0775 {{ rel_path }}/scripts/startup.sh /usr/local/bin/startup.sh
RUN mkdir -p /var/run/rstudio-pm \
    && chmod +x /usr/local/bin/startup.sh \
    && chown rstudio-pm:rstudio-pm /usr/local/bin/startup.sh \
    && chown -R rstudio-pm:rstudio-pm /var/run/rstudio-pm

USER rstudio-pm

RUN echo "source <(rspm completion bash)" >> ~/.bashrc

ENTRYPOINT ["tini", "--"]
CMD ["/usr/local/bin/startup.sh"]
