ARG REGISTRY=docker.io
ARG PYTHON_VERSION="3.12.6"
ARG R_VERSION="4.4.1"
FROM ${REGISTRY}/posit/base:ubuntu2204

### ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive
ARG SCRIPTS_DIR=/opt/posit/scripts
ARG PYTHON_VERSION="3.12.6"
ARG R_VERSION="4.4.1"
ARG PACKAGE_MANAGER_VERSION="2024.08.2-9"

ENV PPM_LICENSE ""
ENV PPM_LICENSE_SERVER ""
ENV PPM_LICENSE_FILE_PATH ""
ENV STARTUP_DEBUG_MODE 0

### Install Apt Packages ###
COPY common/ubuntu/22.04/packages.txt /tmp/packages.txt
RUN $SCRIPTS_DIR/apt.sh --update upgrade \
    && $SCRIPTS_DIR/apt.sh install $(cat /tmp/packages.txt) \
    && rm -f /tmp/packages.txt \
    && $SCRIPTS_DIR/apt.sh --clean

### Install Python packages ###
COPY package-manager/2024.08.2-9/deps/requirements.txt /tmp/requirements.txt
RUN $SCRIPTS_DIR/install_python.sh -r /tmp/requirements.txt -- ${PYTHON_VERSION}

### Install Package Manager 2024.08.2-9 ###
COPY common/ubuntu/scripts/install_package_manager.sh /tmp/install_package_manager.sh
RUN /tmp/install_package_manager.sh \
    && rm -f /tmp/install_package_manager.sh

### Add startup.sh script ###
COPY --chmod=0775 package-manager/2024.08.2-9/scripts/startup.sh /usr/local/bin/startup.sh
RUN mkdir -p /var/run/rstudio-pm \
    && chmod +x /usr/local/bin/startup.sh \
    && chown rstudio-pm:rstudio-pm /usr/local/bin/startup.sh \
    && chown -R rstudio-pm:rstudio-pm /var/run/rstudio-pm

USER rstudio-pm

RUN echo "source <(rspm completion bash)" >> ~/.bashrc

ENTRYPOINT ["tini", "--"]
CMD ["/usr/local/bin/startup.sh"]