
FROM cripittwood.azurecr.io/posit/base:ubuntu2204-min
LABEL org.opencontainers.image.base.name="cripittwood.azurecr.io/posit/base:ubuntu2204-min"


### ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive
ARG SCRIPTS_DIR=/opt/posit/scripts

ARG PACKAGE_MANAGER_VERSION="2024.08.2-9"

ENV PPM_LICENSE ""
ENV PPM_LICENSE_SERVER ""
ENV PPM_LICENSE_FILE_PATH ""
ENV STARTUP_DEBUG_MODE 0

### Install Apt Packages ###
COPY package-manager/2024.08.2-9/deps/ubuntu2204_packages.txt /tmp/ubuntu2204_packages.txt
RUN $SCRIPTS_DIR/apt.sh --update upgrade \
    && $SCRIPTS_DIR/apt.sh install $(cat /tmp/ubuntu2204_packages.txt) \
    && rm -f /tmp/packages.txt \
    && $SCRIPTS_DIR/apt.sh --clean



### Install Package Manager 2024.08.2-9 ###
COPY package-manager/2024.08.2-9/scripts/install_package_manager.sh /tmp/install_package_manager.sh
RUN /tmp/install_package_manager.sh \
    && rm -f /tmp/install_package_manager.sh

### Add startup.sh script ###
COPY --chmod=0775 package-manager/2024.08.2-9/scripts/startup.sh /usr/local/bin/startup.sh
RUN mkdir -p /var/run/rstudio-pm \
    && chmod +x /usr/local/bin/startup.sh \
    && chown rstudio-pm:rstudio-pm /usr/local/bin/startup.sh \
    && chown -R rstudio-pm:rstudio-pm /var/run/rstudio-pm

USER rstudio-pm

RUN echo "source <(rspm completion bash)" >> ~/.bashrc



ENTRYPOINT ["tini", "--"]
CMD ["/usr/local/bin/startup.sh"]