FROM docker.io/library/ubuntu:22.04
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:22.04"

ADD --chmod=750 https://saipittwood.blob.core.windows.net/packages/pti /usr/local/bin/pti

### ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive

ARG PYTHON_VERSION="3.12.1"
ARG R_VERSION="4.4.0"

ARG PACKAGE_MANAGER_VERSION="2024.04.4-35"

ENV PPM_LICENSE ""
ENV PPM_LICENSE_SERVER ""
ENV PPM_LICENSE_FILE_PATH ""
ENV STARTUP_DEBUG_MODE 0

### Install Apt Packages ###
COPY package-manager/2024.04.4-35/deps/ubuntu2204_packages.txt /tmp/ubuntu2204_packages.txt
RUN pti container bootstrap \
    && pti container syspkg upgrade --dist \
    && pti container syspkg install -f /tmp/ubuntu2204_packages.txt \
    && rm -f /tmp/ubuntu2204_packages.txt

 \
### Install R packages ###
RUN pti r install -V ${R_VERSION}
### Install Python packages ###
COPY package-manager/2024.04.4-35/deps/python_requirements.txt /tmp/python_requirements.txt
RUN pti python install -V ${PYTHON_VERSION} -r /tmp/python_requirements.txt \
    && rm -f /tmp/python_requirements.txt


### Install Package Manager 2024.04.4-35 ###
COPY package-manager/2024.04.4-35/scripts/install_package_manager.sh /tmp/install_package_manager.sh
RUN /tmp/install_package_manager.sh \
    && rm -f /tmp/install_package_manager.sh

### Add startup.sh script ###
COPY --chmod=0775 package-manager/2024.04.4-35/scripts/startup.sh /usr/local/bin/startup.sh
RUN mkdir -p /var/run/rstudio-pm \
    && chmod +x /usr/local/bin/startup.sh \
    && chown rstudio-pm:rstudio-pm /usr/local/bin/startup.sh \
    && chown -R rstudio-pm:rstudio-pm /var/run/rstudio-pm

USER rstudio-pm

RUN echo "source <(rspm completion bash)" >> ~/.bashrc


LABEL co.posit.image.tools.python="3.12.1" \
      co.posit.image.tools.r="4.4.0"


ENTRYPOINT ["tini", "--"]
CMD ["/usr/local/bin/startup.sh"]