FROM --platform=linux/amd64 docker.io/library/ubuntu:22.04
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:22.04"

### ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive
ARG PTI_VERSION="0.0.1"
ARG PTI_NO_COLOR="true"
ARG PTI_LOG_FORMAT="json"

ARG PACKAGE_MANAGER_VERSION="2024.08.0-6"

ENV PPM_LICENSE ""
ENV PPM_LICENSE_SERVER ""
ENV PPM_LICENSE_FILE_PATH ""
ENV STARTUP_DEBUG_MODE 0

### Install Posit Tool Installer ###
ADD --chmod=0755 \
    https://github.com/posit-dev/pti/releases/download/v${PTI_VERSION}/pti_${PTI_VERSION}_linux_amd64 \
    /usr/local/bin/pti

### Initialize PTI in container ###
RUN pti init

### Install Apt Packages ###
COPY package-manager/2024.08.0-6/deps/ubuntu2204_packages.txt /tmp/packages.txt
RUN pti syspkg update \
    && pti syspkg upgrade --dist \
    && pti syspkg install -f /tmp/packages.txt \
    && rm -f /tmp/packages.txt



### Install Package Manager 2024.08.0-6 ###
COPY package-manager/2024.08.0-6/scripts/install_package_manager.sh /tmp/install_package_manager.sh
RUN /tmp/install_package_manager.sh \
    && rm -f /tmp/install_package_manager.sh

### Add startup.sh script ###
COPY --chmod=0775 package-manager/2024.08.0-6/scripts/startup.sh /usr/local/bin/startup.sh
RUN mkdir -p /var/run/rstudio-pm \
    && chmod +x /usr/local/bin/startup.sh \
    && chown rstudio-pm:rstudio-pm /usr/local/bin/startup.sh \
    && chown -R rstudio-pm:rstudio-pm /var/run/rstudio-pm

USER rstudio-pm

RUN echo "source <(rspm completion bash)" >> ~/.bashrc



CMD ["/usr/local/bin/startup.sh"]