FROM docker.io/library/ubuntu:22.04
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:22.04"

ADD --chmod=750 https://saipittwood.blob.core.windows.net/packages/pti /usr/local/bin/pti

### ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive

ARG PACKAGE_MANAGER_VERSION="2024.08.0-6"

ENV PPM_LICENSE ""
ENV PPM_LICENSE_SERVER ""
ENV PPM_LICENSE_FILE_PATH ""
ENV STARTUP_DEBUG_MODE 0

### Install Apt Packages ###
COPY package-manager/2024.08.0-6/deps/ubuntu2204_packages.txt /tmp/ubuntu2204_packages.txt
RUN pti container bootstrap \
    && pti container syspkg upgrade --dist \
    && pti container syspkg install -f /tmp/ubuntu2204_packages.txt \
    && rm -f /tmp/ubuntu2204_packages.txt



### Install Package Manager 2024.08.0-6 ###
COPY package-manager/2024.08.0-6/scripts/install_package_manager.sh /tmp/install_package_manager.sh
RUN /tmp/install_package_manager.sh \
    && rm -f /tmp/install_package_manager.sh

### Add startup.sh script ###
COPY --chmod=0775 package-manager/2024.08.0-6/scripts/startup.sh /usr/local/bin/startup.sh
RUN mkdir -p /var/run/rstudio-pm \
    && chmod +x /usr/local/bin/startup.sh \
    && chown rstudio-pm:rstudio-pm /usr/local/bin/startup.sh \
    && chown -R rstudio-pm:rstudio-pm /var/run/rstudio-pm

USER rstudio-pm

RUN echo "source <(rspm completion bash)" >> ~/.bashrc



ENTRYPOINT ["tini", "--"]
CMD ["/usr/local/bin/startup.sh"]