# Build Python using uv in a separate stage
FROM ghcr.io/astral-sh/uv:debian-slim AS python-builder

ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy
ENV UV_PYTHON_INSTALL_DIR=/opt/python
ENV UV_PYTHON_PREFERENCE=only-managed
RUN uv python install 3.12.8
RUN mv /opt/python/cpython-3.12.8-linux-*/ /opt/python/3.12.8


FROM docker.io/library/ubuntu:22.04
LABEL org.opencontainers.image.base.name="docker.io/library/ubuntu:22.04"

### ARG declarations ###
ARG DEBIAN_FRONTEND=noninteractive
ARG PACKAGE_MANAGER_VERSION="2024.11.0-7"

ENV PPM_LICENSE=""
ENV PPM_LICENSE_SERVER=""
ENV PPM_LICENSE_FILE_PATH=""
ENV STARTUP_DEBUG_MODE=0

SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

### Setup environment ###
RUN apt-get update -yqq --fix-missing && \
    apt-get upgrade -yqq && \
    apt-get dist-upgrade -yqq && \
    apt-get autoremove -yqq --purge && \
    apt-get install -yqq --no-install-recommends \
        curl \
        ca-certificates \
        gnupg \
        tar && \
    bash -c "$(curl -1fsSL 'https://dl.posit.co/public/pro/setup.deb.sh')" && \
    apt-get clean -yqq && \
    rm -rf /var/lib/apt/lists/*

### Install Apt Packages ###
COPY package-manager/2024.11/deps/ubuntu2204_packages.txt /tmp/packages.txt
RUN apt-get update -yqq && \
    xargs -a /tmp/packages.txt apt-get install -yqq --no-install-recommends && \
    apt-get clean -yqq && \
    rm -rf /var/lib/apt/lists/*

### Install Python from previous stage ###
COPY --from=python-builder /opt/python /opt/python

### Install Python packages ###
COPY package-manager/2024.11/deps/python_requirements.txt /tmp/requirements.txt
RUN /opt/python/3.12.8/bin/pip install --no-cache-dir --upgrade --break-system-packages \
        -r /tmp/requirements.txt && \
    rm -f /tmp/requirements.txt

### Install R ###
RUN RUN_UNATTENDED=1 R_VERSION=4.4.2 bash -c "$(curl -fsSL https://rstd.io/r-install)" && \
    find . -type f -name '[rR]-4.4.2.*\.(deb|rpm)' -delete

### Install Package Manager 2024.11.0-7 ###
COPY --chmod=0755 package-manager/2024.11/scripts/install_package_manager.sh /tmp/install_package_manager.sh
RUN PYTHON_VERSION=3.12.8 R_VERSION=4.4.2 \
    /tmp/install_package_manager.sh \
    && rm -f /tmp/install_package_manager.sh

### Add startup.sh script ###
COPY --chmod=0775 package-manager/2024.11/scripts/startup.sh /usr/local/bin/startup.sh
RUN mkdir -p /var/run/rstudio-pm \
    && chmod +x /usr/local/bin/startup.sh \
    && chown rstudio-pm:rstudio-pm /usr/local/bin/startup.sh \
    && chown -R rstudio-pm:rstudio-pm /var/run/rstudio-pm

USER rstudio-pm

RUN echo "source <(rspm completion bash)" >> ~/.bashrc

CMD ["/usr/local/bin/startup.sh"]
