name: CI
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*"

concurrency:
  # Only cancel in-progress runs for pull_request events, this prevents cancelling workflows against main or tags
  # A pull_request will reuse the same group thus enabling cancelation, all others receive a unique run_id
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    permissions:
      contents: read
      packages: write

    uses: "posit-dev/images-shared/.github/workflows/bakery-build.yml@ci-workflow"
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    with:
      version: ci-workflow
      dev-versions: "exclude"

  dev:
    name: Dev Build
    permissions:
      contents: read
      packages: write

    uses: "posit-dev/images-shared/.github/workflows/bakery-build.yml@ci-workflow"
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    with:
      version: ci-workflow
      dev-versions: "only"

  status:
    # This is a meta-job, here to express the conditions we require
    # in order to consider a CI run to be successful. This should be
    # the only action checked in the repo settings.
    name: Status
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - build
      - dev

    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
