name: Deprecate Editions

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch: {}

jobs:
  deprecate:
    permissions:
      contents: write
      pull-requests: write
    uses: posit-dev/images-shared/.github/workflows/deprecate-editions.yml@main
    with:
      images: "package-manager"
    secrets:
      CLIENT_ID: ${{ secrets.PPM_AUTOMATION_CLIENT_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PPM_AUTOMATION_PEM }}
