name: Pull Request
on:
  pull_request:
  merge_group:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    if: always()
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 10
    needs:
      - checks
      - production
      - development
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe  # v1.2.2
        id: alls-green
        with:
          jobs: ${{ toJSON(needs) }}
      - if: always() && github.event_name == 'merge_group'
        continue-on-error: true
        uses: posit-dev/images-shared/.github/actions/slack-build-notify@main
        with:
          result: ${{ steps.alls-green.outcome }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

  checks:
    name: Checks
    permissions:
      contents: read
      security-events: write
    uses: posit-dev/images-shared/.github/workflows/checks.yml@worktree-lychee-link-checking

  production:
    name: Production
    permissions:
      contents: read
      packages: write
    uses: posit-dev/images-shared/.github/workflows/bakery-build-pr.yml@main
    with:
      dev-versions: "exclude"

  development:
    name: Development
    permissions:
      contents: read
      packages: write
    uses: posit-dev/images-shared/.github/workflows/bakery-build-pr.yml@main
    with:
      dev-versions: "only"

